language: r
sudo: required
warnings_are_errors: true
env:
  global:
    - CRAN=http://cran.rstudio.com
    - NOT_CRAN=true

r_binary_packages:
  - XML

notifications:
  email:
    on_success: change
    on_failure: change
