language: r
sudo: required
warnings_are_errors: true
env:
  global:
    - NOT_CRAN=true
before_install: echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile

after_success:
- Rscript -e 'covr::codecov()'

r_binary_packages:
  - XML

notifications:
  email:
    on_success: change
    on_failure: change
